# Generated by Django 4.2.7 on 2023-11-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioLaLigaFemenina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(db_column='local')),
                ('visitante', models.CharField(db_column='visitante')),
                ('resultado', models.CharField(db_column='resultado')),
            ],
            options={
                'db_table': 'calendario_laliga_femenina',
            },
        ),
    ]
