# Generated by Django 4.2.7 on 2023-11-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_calendariolaligafemenina'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendariolaliga',
            name='jornada',
            field=models.CharField(db_column='jornada', default=''),
            preserve_default=False,
        ),
    ]
