# Generated by Django 4.2.7 on 2023-11-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticias',
            options={'ordering': ['-fecha']},
        ),
        migrations.AlterModelTable(
            name='noticias',
            table='noticias',
        ),
    ]
