# Generated by Django 4.2.7 on 2023-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscudosBundesliga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='escudos/bundesliga')),
            ],
        ),
        migrations.CreateModel(
            name='EscudosLigue1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='escudos/ligue1')),
            ],
        ),
        migrations.CreateModel(
            name='EscudosPremier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='escudos/premier')),
            ],
        ),
        migrations.CreateModel(
            name='EscudosSeriea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('imagen', models.ImageField(upload_to='escudos/seriea')),
            ],
        ),
        migrations.AlterField(
            model_name='escudoslaliga',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
