# Generated by Django 4.2.7 on 2023-11-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionLaLiga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('posicion', models.IntegerField()),
                ('Puntos', models.IntegerField()),
                ('PJ', models.IntegerField()),
                ('PG', models.IntegerField()),
                ('PE', models.IntegerField()),
                ('PP', models.IntegerField()),
                ('GF', models.IntegerField()),
                ('GC', models.IntegerField()),
            ],
        ),
    ]
