# Generated by Django 4.2.7 on 2023-11-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clasificacionlaliga',
            table='clasificacion_laliga',
        ),
    ]
