# Generated by Django 4.2.7 on 2023-11-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasificacion', '0002_alter_clasificacionlaliga_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='GC',
            field=models.IntegerField(db_column='GC'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='GF',
            field=models.IntegerField(db_column='GF'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='PE',
            field=models.IntegerField(db_column='PE'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='PG',
            field=models.IntegerField(db_column='PG'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='PJ',
            field=models.IntegerField(db_column='PJ'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='PP',
            field=models.IntegerField(db_column='PP'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='Puntos',
            field=models.IntegerField(db_column='puntos'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='nombre_equipo',
            field=models.CharField(db_column='nombre_equipo'),
        ),
        migrations.AlterField(
            model_name='clasificacionlaliga',
            name='posicion',
            field=models.IntegerField(db_column='posicion'),
        ),
    ]
